spring.application.name=MassManagement
server.port=9095
server.servlet.context-path=/mass_management
## Main database - Mysql
spring.datasource.url=jdbc:postgresql://localhost:5432/massmanagement
spring.h2.console.enabled=true
spring.datasource.username=postgres
spring.datasource.password=hakim@123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.threads.virtual.enabled=true
spring.cache.type=simple
# Mail - gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hakimsoftware100@gmail.com
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
resilience4j.ratelimiter.instances.default.limit-refresh-period=1s
resilience4j.ratelimiter.instances.default.limit-for-period=200
resilience4j.ratelimiter.instances.default.timeout-duration=2s
resilience4j.ratelimiter.instances.default.register-health-indicator=true
resilience4j.ratelimiter.instances.default.event-consumer-buffer-size=100
resilience4j.ratelimiter.instances.postRequestRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.postRequestRateLimiter.limit-for-period=100
resilience4j.ratelimiter.instances.postRequestRateLimiter.timeout-duration=2s
resilience4j.ratelimiter.instances.postRequestRateLimiter.register-health-indicator=true
resilience4j.ratelimiter.instances.postRequestRateLimiter.event-consumer-buffer-size=100
# GUI
mass-management.ui.url=http://localhost:5000
